version: '1'

services:
  detectron2:
    build:
      context: .
      dockerfile: Dockerfile
    image: detectron2-app
    container_name: detectron2-container
    volumes:
      - ${INPUT_DIR:-./data/input}:/app/data/input
      - ${OUTPUT_DIR:-./data/output}:/app/data/output
    command: --video /app/data/input/${VIDEO_FILE:-video1.mp4} --output /app/data/output ${EXTRA_ARGS:-"--stats"}
    # Configuración para soporte de GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
